/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author Adriano
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TITULO = new javax.swing.JTextArea();
        Torre1 = new javax.swing.JPanel();
        ooooo = new javax.swing.JLabel();
        oooo = new javax.swing.JLabel();
        ooo = new javax.swing.JLabel();
        oo = new javax.swing.JLabel();
        o = new javax.swing.JLabel();
        Torre2 = new javax.swing.JPanel();
        Torre3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MOVERT2 = new javax.swing.JButton();
        MOVERT3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        MOVERT4 = new javax.swing.JButton();
        MOVERT5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        MOVERT6 = new javax.swing.JButton();
        MOVERT7 = new javax.swing.JButton();
        BS = new javax.swing.JButton();
        BG = new javax.swing.JButton();
        BIJ = new javax.swing.JButton();
        BMP = new javax.swing.JButton();
        MOVERT8 = new javax.swing.JButton();
        IniciarButt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TITULO.setEditable(false);
        TITULO.setColumns(20);
        TITULO.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        TITULO.setRows(5);
        TITULO.setText("              TABLERO\n                HANOI");
        TITULO.setToolTipText("");
        TITULO.setBorder(null);
        TITULO.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 240, 55));

        Torre1.setBackground(new java.awt.Color(0, 153, 153));
        Torre1.setLayout(new java.awt.GridLayout(5, 1));

        ooooo.setText("ooooo");
        Torre1.add(ooooo);

        oooo.setText("oooo");
        Torre1.add(oooo);

        ooo.setText("ooo");
        Torre1.add(ooo);

        oo.setText("oo");
        Torre1.add(oo);

        o.setText("o");
        Torre1.add(o);

        getContentPane().add(Torre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 200, 320));

        Torre2.setBackground(new java.awt.Color(51, 255, 51));
        Torre2.setLayout(new java.awt.GridLayout(5, 1));
        getContentPane().add(Torre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 210, 320));

        Torre3.setBackground(new java.awt.Color(0, 102, 102));
        Torre3.setLayout(new java.awt.GridLayout(5, 1));
        getContentPane().add(Torre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 200, 320));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MOVER A TORRE...");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 481, 109, 23));

        MOVERT2.setBackground(javax.swing.UIManager.getDefaults().getColor("HelpButton.focusedBorderColor"));
        MOVERT2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        MOVERT2.setText("2");
        getContentPane().add(MOVERT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 504, 47, 40));

        MOVERT3.setBackground(javax.swing.UIManager.getDefaults().getColor("HelpButton.focusedBorderColor"));
        MOVERT3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        MOVERT3.setText("3");
        getContentPane().add(MOVERT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 504, 43, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MOVER A TORRE...");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 481, 109, 23));

        MOVERT4.setBackground(javax.swing.UIManager.getDefaults().getColor("HelpButton.focusedBorderColor"));
        MOVERT4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        MOVERT4.setText("1");
        getContentPane().add(MOVERT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 504, 47, 40));

        MOVERT5.setBackground(javax.swing.UIManager.getDefaults().getColor("HelpButton.focusedBorderColor"));
        MOVERT5.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        MOVERT5.setText("3");
        getContentPane().add(MOVERT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 504, 47, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MOVER A TORRE...");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(825, 481, 109, 23));

        MOVERT6.setBackground(javax.swing.UIManager.getDefaults().getColor("HelpButton.focusedBorderColor"));
        MOVERT6.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        MOVERT6.setText("1");
        getContentPane().add(MOVERT6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, 47, 40));

        MOVERT7.setBackground(javax.swing.UIManager.getDefaults().getColor("HelpButton.focusedBorderColor"));
        MOVERT7.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        MOVERT7.setText("2");
        getContentPane().add(MOVERT7, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 500, 47, 40));

        BS.setBackground(javax.swing.UIManager.getDefaults().getColor("HelpButton.focusedBorderColor"));
        BS.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        BS.setText("SALIR");
        getContentPane().add(BS, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 696, 169, 53));

        BG.setBackground(javax.swing.UIManager.getDefaults().getColor("HelpButton.focusedBorderColor"));
        BG.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        BG.setText("GUARDAR");
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 696, 169, 53));

        BIJ.setBackground(javax.swing.UIManager.getDefaults().getColor("HelpButton.focusedBorderColor"));
        BIJ.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        BIJ.setText("INGRESE JUGADOR");
        getContentPane().add(BIJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 637, 169, 53));

        BMP.setBackground(javax.swing.UIManager.getDefaults().getColor("HelpButton.focusedBorderColor"));
        BMP.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        BMP.setText("MOSTRAR PUNTOS");
        getContentPane().add(BMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 637, 169, 53));

        MOVERT8.setBackground(javax.swing.UIManager.getDefaults().getColor("HelpButton.focusedBorderColor"));
        MOVERT8.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        MOVERT8.setText("AGREGAR DISCOS");
        getContentPane().add(MOVERT8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 670, 190, 40));

        IniciarButt.setText("INICIAR");
        getContentPane().add(IniciarButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 660, 80, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    

    public JButton getBG() {
        return BG;
    }

    public JButton getBIJ() {
        return BIJ;
    }

    public JButton getBMP() {
        return BMP;
    }

    public JButton getBS() {
        return BS;
    }

    public JButton getMOVERT2() {
        return MOVERT2;
    }

    public JButton getMOVERT3() {
        return MOVERT3;
    }

    public JButton getMOVERT4() {
        return MOVERT4;
    }

    public JButton getMOVERT5() {
        return MOVERT5;
    }

    public JButton getMOVERT6() {
        return MOVERT6;
    }

    public JButton getMOVERT7() {
        return MOVERT7;
    }

    public JButton getMOVERT8() {
        return MOVERT8;
    }

    public JButton getIniciarButt() {
        return IniciarButt;
    }

    public JPanel getTorre1() {
        return Torre1;
    }
    
        public JPanel getTorre2() {
        return Torre2;
    }

    public JPanel getTorre3() {
        return Torre3;
    }

    public JLabel getDisco1() {
        return o;
    }

    public JLabel getDisco2() {
        return oo;
    }

    public JLabel getDisco3() {
        return ooo;
    }

    public JLabel getDisco4() {
        return oooo;
    }

    public JLabel getDisco5() {
        return ooooo;
    }


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BG;
    private javax.swing.JButton BIJ;
    private javax.swing.JButton BMP;
    private javax.swing.JButton BS;
    private javax.swing.JButton IniciarButt;
    private javax.swing.JButton MOVERT2;
    private javax.swing.JButton MOVERT3;
    private javax.swing.JButton MOVERT4;
    private javax.swing.JButton MOVERT5;
    private javax.swing.JButton MOVERT6;
    private javax.swing.JButton MOVERT7;
    private javax.swing.JButton MOVERT8;
    private javax.swing.JTextArea TITULO;
    private javax.swing.JPanel Torre1;
    private javax.swing.JPanel Torre2;
    private javax.swing.JPanel Torre3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel o;
    private javax.swing.JLabel oo;
    private javax.swing.JLabel ooo;
    private javax.swing.JLabel oooo;
    private javax.swing.JLabel ooooo;
    // End of variables declaration//GEN-END:variables

}
